name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    strategy:
      matrix:
        os: ["ubuntu-20.04", "macos-10.15"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v19
    - uses: cachix/cachix-action@v12
      with:
        name: nathyong
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build --print-build-logs
