name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    matrix:
      include:
        - os: ubuntu-20.04
        - os: macos-10.15
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
    - uses: cachix/cachix-action@v10
      with:
        name: nathyong
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build
